name: Build database

on:
  push:
    branches: [main]
    paths:
      - "packages/*"
      - ".github/workflows/*"
      - "update.sh"

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    name: Update package database
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install tools
        run: sudo apt-get install fakeroot -y
      - name: Import GPG key
        run: |
          echo '${{ secrets.GPG_PRIVATE_KEY }}' | GPG_TTY=$(tty) gpg --batch --import
          mkdir /nonexistent
          chown nobody /nonexistent
          echo '${{ secrets.GPG_PRIVATE_KEY }}' | sudo -u nobody gpg --batch --import
      - name: Build packages
        run: |
          chown -R nobody .
          for PACKAGE in */; do
            cd "$PACKAGE"
            sudo -u nobody DEVKITPRO=$DEVKITPRO DEVKITARM=$DEVKITARM dkp-makepkg -sr
            echo '${{ secrets.GPG_PASSPHRASE }}' | gpg --detach-sign --pinentry-mode loopback --passphrase-fd 0 *.pkg.tar.xz
            cd ..
          done
          chown -R root .
          mkdir /pkgtemp
          mv */*.pkg.tar.xz* /pkgtemp
      - name: Checkout repo branch
        uses: actions/checkout@v3
        with:
          ref: repo
      - name: Create database
        run: |
          rm -f *.{db,sig,tar.gz,tar.xz,.tar.bz2,.tar.zstd}
          mv /pkgtemp/* .
          echo '${{ secrets.GPG_PASSPHRASE }}' | dkp-repo-add --verify --sign dsh-libs.db.tar.gz *.pkg.tar.xz
      - name: Commit to repo
        run: |
          git config user.email "flamekat54@aol.com"
          git config user.name "TWLBot"

          echo "machine github.com" > "$HOME/.netrc"
          echo "  login TWLBot" >> "$HOME/.netrc"
          echo "  password ${{ secrets.GITHUB_TOKEN }}" >> "$HOME/.netrc"

          echo "machine api.github.com" >> "$HOME/.netrc"
          echo "  login TWLBot" >> "$HOME/.netrc"
          echo "  password ${{ secrets.GITHUB_TOKEN }}" >> "$HOME/.netrc"

          git stage .
          if git commit -m "Update package database"; then
            git push origin repo
          fi

