name: Build database

on:
  push:
    branches: ["*"]
    paths:
      - "packages/*"
      - ".github/workflows/*"
      - "update.sh"
  pull_request:
    branches: ["*"]
    paths:
      - "packages/*"
      - ".github/workflows/*"
      - "update.sh"

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    name: Update package database
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install tools
        run: sudo apt-get install fakeroot -y
      - name: Build packages
        run: |
          chown -R nobody packages
          for PACKAGE in packages/*; do
            cd "$PACKAGE"
            sudo -u nobody DEVKITPRO=$DEVKITPRO DEVKITARM=$DEVKITARM dkp-makepkg -sr
            cd ../..
          done
          chown -R root packages
      - name: Create database
        run: |
          cd repo
          rm *
          mv ../packages/*/*.pkg.tar.xz* .
          dkp-repo-add --verify dsh-libs.db.tar.gz *.pkg.tar.xz
      - name: Commit to repo
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          git config user.email "flamekat54@aol.com"
          git config user.name "TWLBot"

          echo "machine github.com" > "$HOME/.netrc"
          echo "  login TWLBot" >> "$HOME/.netrc"
          echo "  password ${{ secrets.GITHUB_TOKEN }}" >> "$HOME/.netrc"

          echo "machine api.github.com" >> "$HOME/.netrc"
          echo "  login TWLBot" >> "$HOME/.netrc"
          echo "  password ${{ secrets.GITHUB_TOKEN }}" >> "$HOME/.netrc"

          git checkout main
          git stage repo
          if git commit -m "Update package database"; then
            git push origin main
          fi

